language: php

php:
    - 5.4
    - 5.5
    - hhvm

before_install:
    - composer self-update
    - composer install --verbose --dev --prefer-source --no-interaction -o

script:
    - ./vendor/bin/phpcs --standard=tests/phpcs.xml library/
    - ./vendor/bin/phpunit --configuration=tests

notifications:
    email: false
